### ISSUE TITLE
Redirect to Campaign Guides Needs to Be Updated to New Guides page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-proxy#71]
On the Help with Reporting and Compliance page (https://transition.fec.gov/index.html) on transition, we have a link for Campaign Guides. It is currently linked to the Help for candidates and committees landing page, and needs to be updated to the Guides page, here: https://www.fec.gov/help-candidates-and-committees/guides/?tab=candidates-and-their-authorized-committees

<img width="686" alt="screen shot 2018-01-31 at 3 28 10 pm" src="https://user-images.githubusercontent.com/31663028/35645875-645ec3f2-069b-11e8-9811-1ec822ccc7dd.png">

**Comment by dorothyyeager** [comment]
Hi Jonella - just noticed this. I actually chose on that page to make the link go to the landing page, didn't want the URL to just mention candidates. On the landing page they can get choose the box for the committee type and then go to the Guide of their type of committee. It can always be changed, but I felt like that was a better way to go - directing to a page for all types, rather than to a page that defaults to the candidate options showing first.
